name: Test
on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Godot
        uses: lihop/setup-godot@v2
        with:
          version: "4.2.1-stable"
      - name: Install just
        uses: taiki-e/install-action@just
      - name: Install addons
        run: just install
      - name: Import assets
        run: godot --editor --headless --quit-after 100 || true
      - name: Run tests
        run: just test
